name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install libboost-dev libboost-program-options-dev
      - name: check code style
        run: |
          make lint
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - name: build and install
        run: |
          make
          sudo make install
