name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends libboost-dev libboost-program-options-dev
      - name: check code style
        run: |
          make lint
          git diff --exit-code
      - name: build and install
        run: |
          make
          sudo make install
          sudo make uninstall
  debian:
    runs-on: ubuntu-20.04
    container: debian:bullseye
    steps:
      - name: install tools
        run: |
          apt-get update
          apt-get install -qq --no-install-recommends devscripts equivs gawk git
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          mk-build-deps -ir -t "apt-get -qq --no-install-recommends"
      - name: prepare changelog
        run: |
          debian/nightly-changelog.sh
        env:
          DISTRO: bullseye
      - name: build package
        run: |
          debuild -us -uc
          mv ../*.deb ~/
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: ~/*.deb
